using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DotNetToolBox.Icons.OpenIconLibrary
{
    public enum IconName
    {
        Exit,
        Internet,
        System,
        AppointmentNew,
        AppointmentSoon,
        ArchiveFiles,
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        Star,
        Bookmark,
        BookmarkNew,
        Clock,
        Colors,
        Configure,
        Db,
        DbAdd,
        DbCommit,
        DbRemove,
        DbStatus,
        DbUpdate,
        Apply,
        Close,
        Error,
        Key,
        Warning,
        Decrypt,
        Encrypt,
        Document,
        DocumentNew,
        DocumentOpen,
        Print,
        DocumentProperties,
        Save,
        SaveAll,
        SaveAs,
        Send,
        Download,
        DocumentEdit,
        Clear,
        Copy,
        Cut,
        Delete,
        Find,
        Paste,
        Rename,
        Package,
        Urgent,
        Home,
        Help,
        Info,
        Hint,
        Add,
        Remove,
        Play,
        Record,
        ChartLine,
        ChartPie,
        Terminal,
        Plugin,
        Settings,
        Trash,
        Display,
        Calendar,
        Filter,
        Refresh
    }
}
